renaming select to inputSelect, textarea to inputTextarea; tweaking make script to exit if tag building fails; adding form-control class to bootstrap inputs; fixing inheritance cases

diff --git a/bin/make b/bin/make
--- a/bin/make
+++ b/bin/make
@@ -3,7 +3,15 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 
 $DIR/makeAllTags $DIR/../src/Base/meta
+if [ $? -ne 0 ]; then
+    echo "Failed to build base tags"
+    exit
+fi
 $DIR/makeAllTags $DIR/../src/Bootstrap/meta
+if [ $? -ne 0 ]; then
+    echo "Failed to build bootstrap tags"
+    exit
+fi
 
 php -f $DIR/makeJsDist.php
 if [ $? -ne 0 ]; then
